/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AnalysisSession = IDL.Record({
  'id' : IDL.Nat,
  'tool' : IDL.Text,
  'filename' : IDL.Text,
  'timestamp' : IDL.Int,
  'resultSummary' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearAllSessions' : IDL.Func([], [], []),
  'createSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteSession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getSessions' : IDL.Func([], [IDL.Vec(AnalysisSession)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AnalysisSession = IDL.Record({
    'id' : IDL.Nat,
    'tool' : IDL.Text,
    'filename' : IDL.Text,
    'timestamp' : IDL.Int,
    'resultSummary' : IDL.Text,
  });
  
  return IDL.Service({
    'clearAllSessions' : IDL.Func([], [], []),
    'createSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteSession' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getSessions' : IDL.Func([], [IDL.Vec(AnalysisSession)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };